In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn import tree
from sklearn.model_selection import GridSearchCV

In [2]:
df=pd.read_csv("F:/final_feature.csv")

In [3]:
df['Rhythm'].value_counts()

SB      3889
GSVT    2307
AFIB    2225
SR      2225
Name: Rhythm, dtype: int64

In [4]:
label = LabelEncoder()
df['label'] = label.fit_transform(df['Rhythm'])

In [5]:
df

,FileName,Rhythm,VentricularRate,AtrialRate,QRSDuration,QTInterval,QTCorrected,RAxis,TAxis,QRSCount,...,"('V6_0_Wavelet absolute mean_0',)","('V6_0_Wavelet absolute mean_1',)","('V6_0_Wavelet absolute mean_2',)","('V6_0_Wavelet absolute mean_3',)","('V6_0_Wavelet absolute mean_4',)","('V6_0_Wavelet absolute mean_5',)","('V6_0_Wavelet absolute mean_6',)","('V6_0_Wavelet absolute mean_7',)","('V6_0_Wavelet absolute mean_8',)",label
0,MUSE_20180113_171327_27000,AFIB,117,234,114,356,496,81,-27,19,...,0.113251,0.338592,0.615693,0.892253,1.113217,1.243881,1.275777,1.219317,1.093314,0
1,MUSE_20180112_073319_29000,SB,52,52,92,432,401,76,42,8,...,0.000495,0.001728,0.005540,0.007774,0.008081,0.007469,0.006525,0.005379,0.003972,2
2,MUSE_20180111_165520_97000,SR,67,67,82,382,403,88,20,11,...,0.006171,0.009190,0.011195,0.017469,0.026112,0.032805,0.033828,0.026007,0.006553,3
3,MUSE_20180113_121940_44000,SB,53,53,96,456,427,34,3,9,...,0.043548,0.125827,0.222832,0.325095,0.425921,0.521494,0.609667,0.689210,0.759547,2
4,MUSE_20180112_122850_57000,AFIB,162,162,114,252,413,68,-40,26,...,0.019536,0.054839,0.098904,0.153417,0.222563,0.309412,0.407235,0.494662,0.543944,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10641,MUSE_20181222_204306_99000,GSVT,196,73,168,284,513,258,244,32,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
10642,MUSE_20181222_204309_22000,GSVT,162,81,162,294,482,110,-75,27,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
10643,MUSE_20181222_204310_31000,GSVT,152,92,152,340,540,250,38,25,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
10644,MUSE_20181222_204312_58000,GSVT,175,178,128,310,529,98,-83,29,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
10645,MUSE_20181222_204314_78000,GSVT,117,104,140,312,435,263,144,19,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1

In [6]:
X=df.drop(columns=['FileName'])
X=X.drop(columns=['Rhythm'])

In [7]:
Y=X[['label']]

In [8]:
Y

       label
0          0
1          2
2          3
3          2
4          0
...      ...
10641      1
10642      1
10643      1
10644      1
10645      1

[10646 rows x 1 columns]

In [9]:
X=X.drop(columns=['label'])

In [10]:
X

,VentricularRate,AtrialRate,QRSDuration,QTInterval,QTCorrected,RAxis,TAxis,QRSCount,QOnset,QOffset,...,"('V5_0_Wavelet absolute mean_8',)","('V6_0_Wavelet absolute mean_0',)","('V6_0_Wavelet absolute mean_1',)","('V6_0_Wavelet absolute mean_2',)","('V6_0_Wavelet absolute mean_3',)","('V6_0_Wavelet absolute mean_4',)","('V6_0_Wavelet absolute mean_5',)","('V6_0_Wavelet absolute mean_6',)","('V6_0_Wavelet absolute mean_7',)","('V6_0_Wavelet absolute mean_8',)"
0,117,234,114,356,496,81,-27,19,208,265,...,1.123937,0.113251,0.338592,0.615693,0.892253,1.113217,1.243881,1.275777,1.219317,1.093314
1,52,52,92,432,401,76,42,8,215,261,...,0.071716,0.000495,0.001728,0.005540,0.007774,0.008081,0.007469,0.006525,0.005379,0.003972
2,67,67,82,382,403,88,20,11,224,265,...,0.036361,0.006171,0.009190,0.011195,0.017469,0.026112,0.032805,0.033828,0.026007,0.006553
3,53,53,96,456,427,34,3,9,219,267,...,1.065030,0.043548,0.125827,0.222832,0.325095,0.425921,0.521494,0.609667,0.689210,0.759547
4,162,162,114,252,413,68,-40,26,228,285,...,2.013842,0.019536,0.054839,0.098904,0.153417,0.222563,0.309412,0.407235,0.494662,0.543944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10641,196,73,168,284,513,258,244,32,177,261,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10642,162,81,162,294,482,110,-75,27,173,254,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10643,152,92,152,340,540,250,38,25,208,284,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10644,175,178,128,310,529,98,-83,29,205,269,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10645,117,104,140,312,435,263,144,19,208,278,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [11]:
X.shape, Y.shape

((10646, 119), (10646, 1))

Decision tree:

In [13]:
#decision tree
tre = tree.DecisionTreeClassifier()

In [16]:
tree_para = {'criterion':['gini','entropy'],'max_depth':[4,5,6,7,8,9,10,11,12,15,20,30]}

In [17]:
clf = GridSearchCV(tre, tree_para, cv=5)

In [18]:
score=cross_validate(clf, X, Y)

In [19]:
print(score)

{'fit_time': array([55.95501733, 50.70399427, 49.1140132 , 47.4829998 , 48.19598699]), 'score_time': array([0.00300026, 0.00300097, 0.00299954, 0.00300002, 0.00300193]), 'test_score': array([0.88967136, 0.88116487, 0.8961954 , 0.86096759, 0.81822452])}

In [20]:
print(np.average(score['test_score']))

0.8692447467015969